name: Check MueLu clang-format

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: DoozyX/clang-format-lint-action@v0.16.2
      with:
        source: './packages/muelu'
        exclude: ''
        extensions: 'cpp,hpp'
        clangFormatVersion: 14
        inplace: true
    - run: git diff HEAD > format_patch.txt
    - run: if [ "$(cat format_patch.txt)" == "" ] ; then rm format_patch.txt ; fi

    - uses: actions/upload-artifact@v4
      id: upload-artf
      if: ${{ hashFiles('format_patch.txt') != '' }}
      with:
        name: MueLu format patch
        path: format_patch.txt
        
    - name: Artifact ID test
      env: 
        ARTF_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.upload-artf.outputs.artifact-id }}
        COMMENT_OUTPUT: Your PR updated files in MueLu, but does not respect the Clang Formatting.  Please apply the patch found [here](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.upload-artf.outputs.artifact-id }})
      run: |
        echo "Artifact ID is ${{ steps.upload-artf.outputs.artifact-id }}"
        echo "Link: https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID/artifacts/${{ steps.upload-artf.outputs.artifact-id }}"
        echo "Atrf URL output = $ARTF_URL"
        echo "Comment output = $COMMENT_OUTPUT"

    - name: Old school comment post
      uses: mshick/add-pr-comment@2.8.1
      if: ${{ hashFiles('format_patch.txt') != '' }}          
      with:
        message: |
          ${{env.COMMENT_OUTPUT}}
      
    
    - name: Post artifact in issue comment
      uses: actions/github-script@v6
      if: ${{ hashFiles('format_patch.txt') != '' }}          
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: ${{env.COMMENT_OUTPUT}}
            })
        
    - uses: actions/github-script@v3
      if: ${{ hashFiles('format_patch.txt') != '' }}
      with:
        script: |
          core.setFailed('Please download and apply the formatting patch! It is located at the bottom of the summary tab for this workflow.')
